[package]
name = "wrapper"
version = "0.1.0"
authors = ["zolkko <zolkko@gmail.com>"]
edition = "2018"

[dependencies]
wrapper-sys = { path = "wrapper-sys" }

[dev-dependencies]

[build-dependencies]

