[package]
name = "wrapper-sys"
version = "0.1.0"
authors = ["zolkko <zolkko@gmail.com>"]
build = "build.rs"
edition = "2018"

[dependencies]

[dev-dependencies]

[build-dependencies]
bindgen = "0.49.2"
cmake = "0.1.40"
